### PR TITLE
Fix tab characters (HT) intermittently lost in output

### LINKED ISSUE #1876: tabs sometimes lost
### Contour Terminal version

0.6.3-master-89481620

### Installer source

GitHub: Source code

### Operating System

Arch Linux

### Architecture

x86-64 / amd64

### Other Software

_No response_

### Steps to reproduce

(first apologies if this is a duplicate - I know we have talked about it years ago and I thought I would find an issue but if its there I missed it).

```
hannah@freq-lap-011~>!!
cat tmp/g-r.txt
fq      git@github.com:frequenz-io/lte_quality.git (fetch)
fq      git@github.com:frequenz-io/lte_quality.git (push)
hannah  git@github.com:hannah-stevenson-frequenz/lte_quality.git (fetch)
hannah  git@github.com:hannah-stevenson-frequenz/lte_quality.git (push)
hannah@freq-lap-011~>cat tmp/g-r.txt
fqgit@github.com:frequenz-io/lte_quality.git (fetch)
fq      git@github.com:frequenz-io/lte_quality.git (push)
hannah  git@github.com:hannah-stevenson-frequenz/lte_quality.git (fetch)
hannah  git@github.com:hannah-stevenson-frequenz/lte_quality.git (push)
```

Note that the second time the first entry is missing its tab. This is intermittent - sometimes it works - and if it doesn't, the one that fails can change. I tried to get debug output but maybe had the wrong flags - let me know if I should reproduce with other debug flags.

```
[2026-02-16 18:41:27.486301] [vt.input] Sending Shift "!" Press.
[2026-02-16 18:41:27.646277] [vt.input] Sending Shift "!" Press.
[2026-02-16 18:41:27.958306] [vt.input] Sending  "Enter" Press.
[2026-02-16 18:41:27.958532] [vt.trace.sequence] control U+0D (Carriage Return)
[2026-02-16 18:41:27.958669] [vt.trace.sequence] control U+0D (Carriage Return)
[2026-02-16 18:41:27.958728] [vt.trace.sequence] control U+0A (Line Feed)
[2026-02-16 18:41:27.960491] [vt.trace.sequence] [primary] text: (15 bytes, 15 cells): "cat tmp/g-r.txt"
[2026-02-16 18:41:27.961538] [vt.trace.sequence] control U+0D (Carriage Return)
[2026-02-16 18:41:27.961591] [vt.trace.sequence] control U+0A (Line Feed)
[2026-02-16 18:41:27.962488] [vt.trace.sequence] [primary] text: (2 bytes, 2 cells): "fq"
[2026-02-16 18:41:27.962545] [vt.trace.sequence] control U+09 (Horizontal Tab)
[2026-02-16 18:41:27.962563] [vt.trace.sequence] [primary] text: (50 bytes, 50 cells): "git@github.com:frequenz-io/lte_quality.git (fetch)"
[2026-02-16 18:41:27.962583] [vt.trace.sequence] control U+0D (Carriage Return)
[2026-02-16 18:41:27.962595] [vt.trace.sequence] control U+0A (Line Feed)
[2026-02-16 18:41:27.962608] [vt.trace.sequence] [primary] text: (2 bytes, 2 cells): "fq"
[2026-02-16 18:41:27.962620] [vt.trace.sequence] control U+09 (Horizontal Tab)
[2026-02-16 18:41:27.962635] [vt.trace.sequence] [primary] text: (49 bytes, 49 cells): "git@github.com:frequenz-io/lte_quality.git (push)"
[2026-02-16 18:41:27.962683] [vt.trace.sequence] control U+0D (Carriage Return)
[2026-02-16 18:41:27.962697] [vt.trace.sequence] control U+0A (Line Feed)
[2026-02-16 18:41:27.962709] [vt.trace.sequence] [primary] text: (6 bytes, 6 cells): "hannah"
[2026-02-16 18:41:27.962718] [vt.trace.sequence] control U+09 (Horizontal Tab)
[2026-02-16 18:41:27.962731] [vt.trace.sequence] [primary] text: (64 bytes, 64 cells): "git@github.com:hannah-stevenson-frequenz/lte_quality.git (fetch)"
[2026-02-16 18:41:27.962745] [vt.trace.sequence] control U+0D (Carriage Return)
[2026-02-16 18:41:27.962754] [vt.trace.sequence] control U+0A (Line Feed)
[2026-02-16 18:41:27.962763] [vt.trace.sequence] [primary] text: (6 bytes, 6 cells): "hannah"
[2026-02-16 18:41:27.962772] [vt.trace.sequence] control U+09 (Horizontal Tab)
[2026-02-16 18:41:27.962784] [vt.trace.sequence] [primary] text: (63 bytes, 63 cells): "git@github.com:hannah-stevenson-frequenz/lte_quality.git (push)"
[2026-02-16 18:41:27.962806] [vt.trace.sequence] control U+0D (Carriage Return)
[2026-02-16 18:41:27.962815] [vt.trace.sequence] control U+0A (Line Feed)
[2026-02-16 18:41:27.963290] [vt.trace.sequence] [primary] text: ">!!"
[2026-02-16 18:41:27.963331] [vt.trace.sequence] [primary] Processing SETMARK        CSI > M
[2026-02-16 18:41:27.963355] [vt.trace.sequence] [primary] Processing SETCWD         OSC 7 /home/hannah
[2026-02-16 18:41:27.963390] [vt.trace.sequence] [primary] Processing ED             CSI J
[2026-02-16 18:41:27.963406] [vt.trace.sequence] [primary] text: (19 bytes, 19 cells): "hannah@freq-lap-011"
[2026-02-16 18:41:27.963421] [vt.trace.sequence] [primary] Processing SGR            CSI 1 m
[2026-02-16 18:41:27.963435] [vt.trace.sequence] [primary] text: (1 bytes, 1 cells): "\x7e"
[2026-02-16 18:41:27.963455] [vt.trace.sequence] [primary] Processing SGR            CSI m
[2026-02-16 18:41:29.502387] [vt.input] Sending  "UpArrow" Press.
[2026-02-16 18:41:29.774317] [vt.input] Sending  "Enter" Press.
[2026-02-16 18:41:29.774598] [vt.trace.sequence] control U+0D (Carriage Return)
[2026-02-16 18:41:29.774628] [vt.trace.sequence] control U+0D (Carriage Return)
[2026-02-16 18:41:29.774642] [vt.trace.sequence] control U+0A (Line Feed)
[2026-02-16 18:41:29.776921] [vt.trace.sequence] [primary] text: (2 bytes, 2 cells): "fq"
[2026-02-16 18:41:29.776969] [vt.trace.sequence] control U+09 (Horizontal Tab)
[2026-02-16 18:41:29.777353] [vt.trace.sequence] [primary] text: (50 bytes, 50 cells): "git@github.com:frequenz-io/lte_quality.git (fetch)"
[2026-02-16 18:41:29.777407] [vt.trace.sequence] control U+0D (Carriage Return)
[2026-02-16 18:41:29.777420] [vt.trace.sequence] control U+0A (Line Feed)
[2026-02-16 18:41:29.777433] [vt.trace.sequence] [primary] text: (2 bytes, 2 cells): "fq"
[2026-02-16 18:41:29.777446] [vt.trace.sequence] control U+09 (Horizontal Tab)
[2026-02-16 18:41:29.777461] [vt.trace.sequence] [primary] text: (49 bytes, 49 cells): "git@github.com:frequenz-io/lte_quality.git (push)"
[2026-02-16 18:41:29.777481] [vt.trace.sequence] control U+0D (Carriage Return)
[2026-02-16 18:41:29.777492] [vt.trace.sequence] control U+0A (Line Feed)
[2026-02-16 18:41:29.777504] [vt.trace.sequence] [primary] text: (6 bytes, 6 cells): "hannah"
[2026-02-16 18:41:29.777516] [vt.trace.sequence] control U+09 (Horizontal Tab)
[2026-02-16 18:41:29.777533] [vt.trace.sequence] [primary] text: (64 bytes, 64 cells): "git@github.com:hannah-stevenson-frequenz/lte_quality.git (fetch)"
[2026-02-16 18:41:29.777575] [vt.trace.sequence] control U+0D (Carriage Return)
[2026-02-16 18:41:29.777588] [vt.trace.sequence] control U+0A (Line Feed)
[2026-02-16 18:41:29.777600] [vt.trace.sequence] [primary] text: (6 bytes, 6 cells): "hannah"
[2026-02-16 18:41:29.777611] [vt.trace.sequence] control U+09 (Horizontal Tab)
[2026-02-16 18:41:29.777628] [vt.trace.sequence] [primary] text: (63 bytes, 63 cells): "git@github.com:hannah-stevenson-frequenz/lte_quality.git (push)"
[2026-02-16 18:41:29.777647] [vt.trace.sequence] control U+0D (Carriage Return)
[2026-02-16 18:41:29.777658] [vt.trace.sequence] control U+0A (Line Feed)
[2026-02-16 18:41:29.777670] [vt.trace.sequence] [primary] text: ">cat tmp/g-r.txt"
[2026-02-16 18:41:29.777686] [vt.trace.sequence] [primary] Processing SETMARK        CSI > M
[2026-02-16 18:41:29.777704] [vt.trace.sequence] [primary] Processing SETCWD         OSC 7 /home/hannah
[2026-02-16 18:41:29.777780] [vt.trace.sequence] [primary] Processing ED             CSI J
[2026-02-16 18:41:29.777801] [vt.trace.sequence] [primary] text: (19 bytes, 19 cells): "hannah@freq-lap-011"
[2026-02-16 18:41:29.777816] [vt.trace.sequence] [primary] Processing SGR            CSI 1 m
[2026-02-16 18:41:29.777830] [vt.trace.sequence] [primary] text: (1 bytes, 1 cells): "\x7e"
[2026-02-16 18:41:29.777860] [vt.trace.sequence] [primary] Processing SGR            CSI m
```

I will attach the file I am catting but it is just the captured output of `git remote -v show`. The bug also occurs if I just run the command repeatedly.

[g-r.txt](https://github.com/user-attachments/files/25347274/g-r.txt)

### Expected Behavior

_No response_

### Actual Behavior

tab is not always rendered

### Additional notes

* sometimes the debug logs miss a mention of printing one of the strings. from another run:

```
[2026-02-16 18:31:22.614520] [vt.input] Sending  "Enter" Press.
[2026-02-16 18:31:22.617437] [vt.trace.sequence] control U+0D (Carriage Return)
[2026-02-16 18:31:22.617508] [vt.trace.sequence] control U+0D (Carriage Return)
[2026-02-16 18:31:22.617520] [vt.trace.sequence] control U+0A (Line Feed)
[2026-02-16 18:31:22.623473] [vt.trace.sequence] control U+09 (Horizontal Tab)
[2026-02-16 18:31:22.623543] [vt.trace.sequence] control U+0D (Carriage Return)
[2026-02-16 18:31:22.623555] [vt.trace.sequence] control U+0A (Line Feed)
[2026-02-16 18:31:22.623570] [vt.trace.sequence] [primary] text: (2 bytes, 2 cells): "fq"
[2026-02-16 18:31:22.623582] [vt.trace.sequence] control U+09 (Horizontal Tab)
[2026-02-16 18:31:22.623597] [vt.trace.sequence] [primary] text: (49 bytes, 49 cells): "git@github.com:frequenz-io/lte_quality.git (push)"
[2026-02-16 18:31:22.623614] [vt.trace.sequence] control U+0D (Carriage Return)
[2026-02-16 18:31:22.623624] [vt.trace.sequence] control U+0A (Line Feed)
```
there should have been a `(fetch)` line between the enter and the `(push)` line. This is intermittent.

* I can re-run the `cat` using `!!` for ever and I won't see the bug. Using Up-Arrow and it happens frequently. If I have done a lot of `!!` then almost always first time I use Up-Arrow (where n is very small). As seen above.

### PR DESCRIPTION
**Pull request by christianparpart**
Fixes bulk text parser skipping C0 controls after scanned text, and tab cursor movement not filling cells with spaces.

Closes #1876

### CODE REVIEW

File: src/vtbackend/Screen.cpp [hunk 1]
```diff
@@ -1621,6 +1621,9 @@ void Screen<Cell>::moveCursorToNextTab()
     // TODO: respect HTS/TBC
 
     static_assert(TabWidth > ColumnCount(0));
+
+    auto n = ColumnCount(0);
```
Comment (Yaraslaut) [inline src/vtbackend/Screen.cpp]: please provide a readable name

File: src/vtbackend/Screen.cpp [hunk 2]
```diff
@@ -1631,21 +1634,32 @@ void Screen<Cell>::moveCursorToNextTab()
...
     }
+
+    if (n > ColumnCount(0))
+    {
+        // Fill intermediate cells with spaces to ensure TrivialLineBuffer consistency.
+        // Without this, the cursor advances but the cell buffer doesn't reflect the gap,
+        // causing tabs to be visually lost during rendering.
+        auto const startCol = _cursor.position.column;
+        auto& line = currentLine();
+        for (auto i = ColumnCount(0); i < n; ++i)
```
Comment (Yaraslaut) [inline src/vtbackend/Screen.cpp]: i guess iota should work here

File: src/vtparser/Parser-impl.h [hunk 3]
```diff
@@ -474,13 +474,26 @@ auto Parser<EventListener, TraceStateChanges>::parseBulkText(char const* begin,
...
-        if (input != end && *input == '\n')
-            _eventListener.execute(*input++);
+        // C0 Execute range: 0x00-0x17, 0x19, 0x1C-0x1F
+        // Excluded: 0x18 (CAN) and 0x1A (SUB) — trigger state transitions (Ground + Ignore)
+        // Excluded: 0x1B (ESC) — transitions to Escape state
+        auto const* current = _scanState.next;
+        while (current != end)
+        {
+            auto const ch = static_cast<uint8_t>(*current);
+            if (ch <= 0x17 || ch == 0x19 || (ch >= 0x1C && ch <= 0x1F))
```
Comment (Yaraslaut) [inline src/vtparser/Parser-impl.h]: I wounder, can we make it faster, previously we where checking for one character, now we check for multiple available options and ranges, is it possible to construct a bit mask of this range to compare in a single operation?
