### PR TITLE
Trying to fix CLI.

### LINKED ISSUE #678: Cannot start with "Unhandled error caught. Unexpected index"
### Contour Terminal version

0.3.2-unreleased-master-db284983

### Installer source

Github: source code cloned

### Operating System

Ubuntu Linux 20.04

### Architecture

x86-64

### Other Software

_No response_

### Steps to reproduce

```
$ rm -fr build && cmake -s . -B build && cmake --build build
$ ./build/src/contour/contour
```

### Expected Behavior

Contour Terminal Emulator 0.3.1.200 (from github release page deb package) can start.

Note: In my environment, the following message reported but it seems not to relate to this problem.

```
[error] Superfluous config key found: profiles.main.bold_is_bright
[error] Superfluous config key found: profiles.main.cursor
[error] Superfluous config key found: profiles.main.normal_mode.cursor
[error] Superfluous config key found: profiles.main.normal_mode
[error] Superfluous config key found: profiles.main.visual_mode.cursor
[error] Superfluous config key found: profiles.main.visual_mode
```

### Actual Behavior

Contour Terminal Emulator 0.3.2-unreleased-master-db284983 cannot start.

```
[error] Superfluous config key found: profiles.main.bold_is_bright
[error] Superfluous config key found: profiles.main.cursor
Unhandled error caught. Unexpected index% 
```

### Additional notes

_No response_

### PR DESCRIPTION
**Pull request by christianparpart**
This will also fix #678.

### CODE REVIEW

File: src/contour/ContourGuiApp.cpp [hunk 1]
```diff
@@ -136,7 +136,7 @@ crispy::cli::Command ContourGuiApp::parameterDefinition() const
 #endif
                 CLI::Option {
                     CLI::OptionName { 'e', "execute" },
-                    CLI::Value { "" },
+                    CLI::Value { ""s },
```
Comment (christianparpart) [inline src/contour/ContourGuiApp.cpp:139]: That's the critical part of this PR.
