### PR TITLE
Fix build on debian 11

### LINKED ISSUE #848: Error when trying to compile - missing install-deps.sh support for Debian 11 Linux
### Contour Terminal version

master, at 6e047fd

### Installer source

Github: source code cloned

### Operating System

debian 11 (bullseye)

### Architecture

x86-64

### Other Software

_No response_

### Steps to reproduce

1. Clone repo and cd into it.
2. Follow source compilation instructions:
3. run `./scripts/install-deps.sh`
4. run `mkdir build`
5. run `cmake -S . -B build`
6. run `cmake --build build/`

### Expected Behavior

Expected the program to be compiled.

### Actual Behavior

Got error message:
```
[  1%] Building CXX object _deps/sources/libunicode-44969c6d80e44a4731b584d047ba108769926835/src/unicode/CMakeFiles/unicode.dir/emoji_segmenter.cpp.o
In file included from /home/myusername/contour/_deps/sources/libunicode-44969c6d80e44a4731b584d047ba108769926835/src/unicode/emoji_segmenter.cpp:15:
/home/myusername/contour/_deps/sources/libunicode-44969c6d80e44a4731b584d047ba108769926835/src/unicode/emoji_segmenter.h:113:87: error: expected class-name before ‘{’ token
  113 | t::formatter<unicode::PresentationStyle>: fmt::ostream_formatter {};
      |                                                                  ^

gmake[2]: *** [_deps/sources/libunicode-44969c6d80e44a4731b584d047ba108769926835/src/unicode/CMakeFiles/unicode.dir/build.make:108: _deps/sources/libunicode-44969c6d80e44a4731b584d047ba108769926835/src/unicode/CMakeFiles/unicode.dir/emoji_segmenter.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:398: _deps/sources/libunicode-44969c6d80e44a4731b584d047ba108769926835/src/unicode/CMakeFiles/unicode.dir/all] Error 2
gmake: *** [Makefile:171: all] Error 2
```

### Additional notes

_No response_

### PR DESCRIPTION
**Pull request by Yaraslaut**
Fixes #848

### CODE REVIEW

File: scripts/install-deps.sh [hunk 1]
```diff
@@ -432,9 +432,13 @@ main()
         pop)
             install_deps_popos
             ;;
-        ubuntu|neon|debian)
+        ubuntu|neon)
             install_deps_ubuntu
             ;;
+        debian)
+            install_deps_ubuntu
+            fetch_and_unpack_fmtlib
```
Comment (christianparpart) [inline scripts/install-deps.sh:440]: Oha, interesting. And that's because Debian ships with a too told fmtlib, I assume?

**Review by christianparpart — DISMISSED** [review]

File: scripts/install-deps.sh (hunk 1 above)
Comment (Yaraslaut) [reply scripts/install-deps.sh:440]: Indeed

**Review by christianparpart — APPROVED** [review]
