### PR TITLE
Fixes `show_title_bar` config option

### LINKED ISSUE #1153: show_title_bar options doesn't work as expected
### Contour Terminal version

Contour Terminal Emulator 0.3.13-master-59df9d6b

### Installer source

Github: source code cloned

### Operating System

Windows 11 wsl2 Arch

### Architecture

x86-64

### Other Software

_No response_

### Steps to reproduce

Setting the show_title_bar option to true:
image

set to false:
image

### Expected Behavior

When I set show_title_bar option to false, title will disappear.

### Actual Behavior

When I set show_title_bar option to false, title still exit.

### Additional notes

_No response_

### PR DESCRIPTION
**Pull request by Utkarsh-khambra**
Fixes #1153, is this the correct way to solve this in QML world?

### CODE REVIEW

**Review by Yaraslaut — APPROVED** [review]
LGTM, tested it on ubuntu vm

File: src/contour/display/TerminalWidget.cpp [hunk 1]
```diff
@@ -297,7 +297,7 @@ void TerminalWidget::setSession(TerminalSession* newSession)
 
     session_->start();
 
-    framelessWidget_ = !profile().show_title_bar;
+    window()->setFlag(Qt::FramelessWindowHint, !profile().show_title_bar);
```
Comment (christianparpart) [inline src/contour/display/TerminalWidget.cpp:300]: good catch

**Review by christianparpart — APPROVED** [review]
LGTM. Many thanks!
