### PR TITLE
Resets all empty cells on receiving `GraphicsRendition::Reset`

### LINKED ISSUE #706: Resizing window messes up neovim background color
### Contour Terminal version

0.3.2-unreleased-master-091f56a3

### Installer source

Github: source code cloned

### Operating System

Fedora Linux 35

### Architecture

x86-64

### Other Software

NeoVim 0.7

### Steps to reproduce

1. Start contour in smaller window.
2. Open some file in nvim.
3. Maximize the contour window.

### Expected Behavior

Screenshot from 2022-05-29 12-06-39

### Actual Behavior

Screenshot from 2022-05-29 12-07-20

### Additional notes

_No response_

### PR DESCRIPTION
**Pull request by Utkarsh-khambra**
fixes #706.

### CODE REVIEW

File: src/terminal/Terminal.cpp [hunk 1]
```diff
@@ -1235,7 +1235,11 @@ void Terminal::setGraphicsRendition(GraphicsRendition _rendition)
     // 3.) clear some bits &= ~
     switch (_rendition)
     {
-        case GraphicsRendition::Reset: state_.cursor.graphicsRendition = {}; break;
+        case GraphicsRendition::Reset:
```
Comment (christianparpart) [inline src/terminal/Terminal.cpp:1238]: Oh @Utkarsh-khambra. Thanks for having this found! :)

Comment (christianparpart) [reply src/terminal/Terminal.cpp:1238]: I wonder what the semantics here are. How did you find this?

**Review by christianparpart — APPROVED** [review]
