### PR TITLE
Handle case when config file is corrupted

### LINKED ISSUE #886: Wrong config file crashes contour
### Contour Terminal version

master a9742e

### Installer source

Github: source code cloned

### Operating System

Manjaro Linux

### Architecture

x86-64

### Other Software

_No response_

### Steps to reproduce

Make config file unreadable by yaml 
As an example : 
 * shell: "fish

### Expected Behavior

loads default configuration with message about error in present configuration file

### Actual Behavior

crashes

### Additional notes

I noticed that TerminalSession have some error handling on configure loading while  ContourGuiApp does not. 
Crash is happening here https://github.com/contour-terminal/contour/blob/a9742e99ec868d109d5df0e8934d385b2c151e89/src/contour/ContourGuiApp.cpp#L283

### PR DESCRIPTION
**Pull request by Yaraslaut**
## Description

Describe your changes in detail

```markdown
Added exception handling on wrong read of provided config file
by creation of valid configuration file and loading it
```

## Motivation and Context

Why is this change required? What problem does it solve?

Fixes  #886 
## How Has This Been Tested?

- [x] Please describe how you tested your changes.
- - checked that on bad configure file contour will create new configure file and load it
- [ ] see how your change affects other areas of the code, etc.

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

- [x] I have read the [**`CONTRIBUTING`**](https://github.com/contour-terminal/contour/blob/master/CONTRIBUTING.md) document in my spoken language, and understand the terms
- [ ] I have updated (or added) the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] I have gone through all the steps, and have thoroughly read the instructions

### CODE REVIEW

**Comment by christianparpart** [comment]
Many thanks! :)

File: src/contour/Config.cpp [hunk 1]
```diff
@@ -1626,9 +1626,19 @@ void loadConfigFromFile(Config& _config, FileSystem::path const& _fileName)
...
+    YAML::Node doc;
+    try
+    {
+        doc = YAML::LoadFile(_fileName.string());
+    }
+    catch (exception const& e)
+    {
+        errorlog()("Configuration file is corrupted. {}", e.what());
+        auto _newfileName = _fileName;
+        _newfileName.replace_filename("default_contour.yml");
```
Comment (christianparpart) [inline src/contour/Config.cpp:1638]:
```suggestion
        auto newfileName = _fileName;
        newfileName.replace_filename("default_contour.yml");
```

**Review by christianparpart — APPROVED** [review]
Just a very minor naming change preference.

**Comment by christianparpart** [comment]
lol. I just realized that tests are failing.

on osx we use boost. maybe we don't need boost on osx anymore. and boost doesn't have the `replace_filename` function so it seems.

We could try disabling using boost on osx.

**Comment by Yaraslaut** [comment]
> lol. I just realized that tests are failing.
> 
> on osx we use boost. maybe we don't need boost on osx anymore. and boost doesn't have the `replace_filename` function so it seems.
> 
> We could try disabling using boost on osx.

indeed, but its also used on ubuntu 18 and i assume we can not get rid of it so easily

**Comment by christianparpart** [comment]
> > lol. I just realized that tests are failing.
> > on osx we use boost. maybe we don't need boost on osx anymore. and boost doesn't have the `replace_filename` function so it seems.
> > We could try disabling using boost on osx.
> 
> indeed, but its also used on ubuntu 18 and i assume we can not get rid of it so easily

I've done that in #888 already and merged it as all tests passed. That should help you. :pray: (do `git fetch && git rebase origin/master`).

**Comment by christianparpart** [comment]
EDIT: **F**. Forgot about Ubuntu 18.04. that's still using Boost (lol).

**Comment by christianparpart** [comment]
@Yaraslaut please drop your commit 4153eca845e785c88819e204b71337dcfe3b1d68 and do a `git fetch && git rebase -i origin/master` and you should be good to go. 

Latest master contains almost no trace to boost-filesystem anymore (The only thing left is stdfs.h and FilesystemResolver.cmake)
