### PR TITLE
Now moves cursor vertically for sixel newlines even if there is no sixel

### LINKED ISSUE #822: no vertical cursor progression on GLFs (sixel)
### Contour Terminal version

0.3.4.223

### Installer source

GitHub: release page

### Operating System

Ubuntu 18 LTS

### Architecture

x86-64

### Other Software

_No response_

### Steps to reproduce

Plz see https://github.com/jerch/xterm-addon-image/issues/37 for details on the issue. There is also this [testscript](https://github.com/hackerb9/vt340test/blob/main/jerch/gcrglf.sh) done by @hackerb9 to check TE behavior.

### Expected Behavior

GLFs from sixel should advance the text cursor to the bottom, if sixel scrolling is on.

### Actual Behavior

Currently there is no text cursor progression from multiple GLFs.

### Additional notes

(@Utkarsh-khambra  This is the follow-up from #820.)

### PR DESCRIPTION
**Pull request by Utkarsh-khambra**
fixes #822

To test this use [this script](https://github.com/hackerb9/vt340test/blob/main/jerch/gcrglf.sh). Since the script requires cell height to be 20px, you can change font size to be 11 in default config with monospace font family.
Screenshot from 2022-09-20 22-53-58

### CODE REVIEW

**Comment by christianparpart** [comment]
Many thanks!

@Utkarsh-khambra with that, I don't think we do not need the configuration option `images.sixel_cursor_conformance` (bool) anymore as I was clearly misunderstanding/misreading/missing some of the Sixel documentation back in the days. I think it's save to completely get rid of that config option. ;)

File: src/terminal/SixelParser.cpp [hunk 1]
```diff
@@ -477,6 +476,12 @@ void SixelImageBuilder::render(int8_t _sixel)
 
 void SixelImageBuilder::finalize()
 {
+    if (unbox<int>(size_.height) == 1)
+    {
+        size_.height = Height::cast_from(sixelCursor_.line.value);
```
Comment (christianparpart) [inline src/terminal/SixelParser.cpp:481]:
```suggestion
        size_.height = Height::cast_from(sixelCursor_.line);
```

File: src/terminal/SixelParser_test.cpp [hunk 2]
```diff
@@ -338,3 +338,17 @@ TEST_CASE("SixelParser.newline", "[sixel]")
         }
     }
 }
+
+TEST_CASE("SixelParser.vertical_cursor_advance", "[sixel]")
+{
+    auto constexpr defaultColor = RGBAColor { 0, 0, 0, 255 };
+    SixelImageBuilder ib(
+        { Width(5), Height { 30 } }, 1, 1, defaultColor, std::make_shared<SixelColorPalette>(16, 256));
```
Comment (christianparpart) [inline src/terminal/SixelParser_test.cpp:346]: Maybe a copy'n'paste thing, but there's a style breakage. Width is using `()` whereas Height is using `{}`. both solution work, but maybe only one should be used for consistency.

File: src/terminal/Screen.cpp [hunk 3]
```diff
@@ -1643,7 +1643,7 @@ void Screen<Cell>::renderImage(shared_ptr<Image const> _image,
             cell.setImageFragment(rasterizedImage, CellLocation { offset.line, offset.column });
             cell.setHyperlink(_state.cursor.hyperlink);
         };
-        moveCursorTo(_topLeft.line + unbox<int>(linesToBeRendered) - 1, _topLeft.column);
+        moveCursorTo(_topLeft.line + unbox<int>(linesToBeRendered), _topLeft.column);
```
Comment (Utkarsh-khambra) [inline src/terminal/Screen.cpp:1646]: from [this test](https://github.com/hackerb9/vt340test/blob/main/j4james/cursor_position.sh#L3-L8) 
> Test of the text cursor position after a Sixel image is output.
 On a genuine VT340, after an image is output, the text cursor position is
 set to the same row as the top of the final sixel line (regardless of
 whether anything is output on that line). The column position remains
 unchanged, i.e. it should align with the left of the image.

@christianparpart  this change should place the ansi cursor to last sixel row, right?

Comment (christianparpart) [reply src/terminal/Screen.cpp:1646]: that is how i read it. any objections, @jerch?

Comment (Utkarsh-khambra) [reply src/terminal/Screen.cpp:1646]: If that's the case I think this is ready to merge.

Comment (jerch) [reply src/terminal/Screen.cpp:1646]: I think "top of final sixel line" here means to clip the text cursor into the text row, wherever the first of the 6 pixel line of the last sixel band ended up above. So its not the last line (sixth pixel line), but the first one determining it. Note that this has a weird consequence, if the last sixel band is not perfectly mapped on text line borders, possibly cutting off lower pixel rows, or not trigger scrolling at the end of the screen.
My impl still usees the last pixel line for this, but I prolly will change that.

Comment (Utkarsh-khambra) [reply src/terminal/Screen.cpp:1646]: So that means you may overwrite pixels in the last sixel line, if you print text just after drawing a sixel image.

Comment (jerch) [reply src/terminal/Screen.cpp:1646]: Yes thats how I understand it so far. But lets see if it gets confirmed...

Comment (hackerb9) [reply src/terminal/Screen.cpp:1646]: The VT340 definitely does overwrite pixels in the last sixel line, but the cases which trigger it happen very rarely as long as a text newline is sent after the sixel image. Here is an image from some of the [testing](https://github.com/hackerb9/vt340test/blob/main/sixeltests/textcursor.sh) I had done to figure out where the text cursor would be positioned based on line endings (only NL, only GNL, or neither). 
Test of Graphics NL and Text NL after sixel images of different height

First, I should state that it seems like the intention was for Sixel images to _not_ include a GLF at the end, but for there to be a text LF after the image if text or another image is going to be written. As @j4james pointed out to me, this allows one to show a full screen sixel image without causing scrolling. 

Second, when only LF is used at the end of the sixel data, 90% of the time there will be no overwrite. In actual practice, the glitch is much rarer than 10%. That is because people usually have images heights that are divisible by ten or a power of two or the character cell height, none of which can trigger what I call the [VT340 text cursor glitch](https://github.com/hackerb9/vt340test/blob/main/glitches.md#text-cursor-is-left-one-row-too-high-for-certain-sixel-heights). 

Personally, I think it is a programming mistake in the VT340 firmware since I cannot see anything in the documentation that would tip off an application developer to expect that behaviour. And, there does not appear to be any point to it. 

I am not sure how to emulate it, but you can predict it on the VT340. For a sixel image of height $h$, let $a=(h-1)\bmod6$ and $b=(h-1)\bmod20$, then, the text will overlap the image when $a>b$.

Comment (j4james) [reply src/terminal/Screen.cpp:1646]: @hackerb9 If you want to see some serious overlap, try this:

    echo -e '\eP1q#"60;1#1!360~\e\\'

**Comment by Utkarsh-khambra** [comment]
Thanks everybody for help in this. I got it to output similar image for [this test as well](https://github.com/hackerb9/vt340test/blob/main/sixeltests/textcursor.sh), only discrepancy I see is with horizontal alignment but I am pretty sure this is because contour has 9px wide cells for my testing config.
Screenshot from 2022-09-22 12-51-54

**Review by christianparpart — APPROVED** [review]
Thanks @Utkarsh-khambra for your work, and thanks @jerch, @hackerb9 and @j4james for your very valuable feedback and the joined discussion over here. :-)

**Comment by hackerb9** [comment]
> Thanks everybody for helping me in this. I got it to output similar image for [this test as well](https://github.com/hackerb9/vt340test/blob/main/sixeltests/textcursor.sh), only discrepancy I see is with horizontal alignment but I am pretty sure this is because contour has 9px wide cells for my testing config. Screenshot from 2022-09-22 12-51-54

Wow! I did not expect anybody would replicate that behaviour and I am impressed. I do think it is a firmware bug that a text newline is not always sufficient to separate sixels from text and I suggest new terminals, like Contour, may want to make precise bug-for-bug VT340 compatibility available but disabled by default.

By the way, now that you've duplicated the overlap glitch, how is it affected when the size of the font goes up? If I'm correct, anything taller than 10×20 will reduce the percentage of "bad" image sizes that cause overlap.

**Comment by Utkarsh-khambra** [comment]
> may want to make precise bug-for-bug VT340 compatibility available but disabled by default.

That's a good suggestion.
Here are some tests that I did

<table>
<tr>
<th> Cell Height</th>
<th> Overlap </th>
 </tr>
<tr>
<td>15</td> <td>No</td>
</tr>
<tr>
<td>17</td> <td>No</td>
</tr>
<tr>
<td>18</td> <td>No</td>
</tr>
<tr>
<td>23</td> <td>No</td>
</tr>
<tr>
<td>25</td> <td>No</td>
</tr>
<tr>
<td>27</td> <td>Yes</td>
</tr>
<tr>
<td>28</td> <td>Yes</td>
</tr>
<tr>
<td>30</td> <td>No</td>
</tr>
<tr>
<td>31</td> <td>No</td>
</tr>
<tr>
<td>33</td> <td>No</td>
</tr>
<tr>
<td>35</td> <td>No</td>
</tr>
<tr>
<td>36</td> <td>No</td>
</tr>
<tr>
<td>38</td> <td>No</td>
</tr>
<tr>
<td>40</td> <td>Yes</td>
</tr>
<tr>
<td>41</td> <td>Yes</td>
</tr>
<tr>
<td>43</td> <td>No</td>
</tr>
<tr>
<td>44</td> <td>No</td>
</tr>
<tr>
<td>46</td> <td>No</td>
</tr>
<tr>
<td>48</td> <td>No</td>
</tr>
<tr>
<td>49</td> <td>No</td>
</tr>
<tr>
<td>51</td> <td>No</td>
</tr>
<tr>
<td>53</td> <td>No</td>
</tr>
<tr>
<td>54</td> <td>No</td>
</tr>
<tr>
<td>56</td> <td>No</td>
</tr>
<tr>
<td>57</td> <td>No</td>
</tr>
<tr>
<td>58</td> <td>No</td>
</tr>
<tr>
<td>61</td> <td>No</td>
</tr>
<tr>
<td>62</td> <td>No</td>
</tr>
<tr>
<td>64</td> <td>No</td>
</tr>
</table>

**Comment by hackerb9** [comment]
> > may want to make precise bug-for-bug VT340 compatibility available but disabled by default.
> 
> That's a good suggestion. Here are some tests that I did [...]

That looks close, but not what I would have predicted. You're only testing image heights 84 and 96, right?

If we can extrapolate from the VT340 glitch, I would expect the overlap bug to occur when

$$
(h_i-1)\bmod6 > (h_i-1)\bmod h_c
$$

where $h_i$ is the height of the image and $h_c$ is the height of the character cell. On a VT340, $h_c$ is fixed at $20$. 

With that formula, a character cell of height 23 would have overlap and 28 would not. It's possible my formula is wrong.

But, I wouldn't spend too much time trying to extend this bug to modern terminals. It's not like there is any compatibility to worry about and it'll only cause application developers grief as they have to implement workarounds to not overlap images.

**Comment by j4james** [comment]
The VT340's behavior may not be to your liking, but it's not a bug or a glitch. It actually serves a very useful purpose when you're working with images that you want to align on text boundaries.

For example, if you want to output an image that is exactly one text cell in height, you need to output 4 sixel bands (24px height) with the last 4 pixels being transparent. If you end that with a GNL, the text cursor is exactly below the image.

Similarly if you want an image two text cells in height, it's 7 sixel bands (42px height) with the last 2 pixels transparent. And for an image three text cells in height, it's exactly 6 sixel bands (60px height).

In every case the text cursor ends up exactly below the visible portion of the image, overwriting only the transparent pixels. And if you leave off the final GNL, you can get the text cursor on the bottom row of the image instead.

Example test cases:

```
echo -en '\eP9;1q#1!800~-!800~-!800~-!800B-\e\\'
echo -en '\eP9;1q#1!800~-!800~-!800~-!800~-!800~-!800~-!800N-\e\\'
echo -en '\eP9;1q#1!800~-!800~-!800~-!800~-!800~-!800~-!800~-!800~-!800~-!800~-\e\\'
```

Please do not try to "fix" sixel. If you don't like it, and feel the need to change the standard, rather put that effort into a new graphics protocol instead.

**Comment by hackerb9** [comment]
> Please do not try to "fix" sixel. If you don't like it, and feel the need to change the standard, rather put that effort into a new graphics protocol instead.

I respectfully disagree with you, but I also see that one of us is misunderstanding the problem. It's probably me and I want to understand, so let's discus that on a new bug so as to not clutter up this one: https://github.com/hackerb9/vt340test/issues/25.
