### PR TITLE
[Vi] Fix y0 crash.

### LINKED ISSUE #1801: VI normal mode `y0` causes a crash
# Steps to reproduce

1. start Contour
2. get into normal mode
3. type `y0`

this causes a crash, interestingly.

### PR DESCRIPTION
**Pull request by christianparpart**
Closes #1801

### CODE REVIEW

File: src/vtbackend/ViCommands.cpp [hunk 1]
```diff
@@ -349,10 +349,8 @@ void ViCommands::executeYank(ViMotion motion, unsigned count)
             break;
         }
         default: {
-            auto const [from, to] = translateToCellRange(motion, count);
-            // motion is inclusive but for yank we want to exclude the last cell which is the first cell of
-            // the next word
-            executeYank(from, { .line = to.line, .column = to.column - 1 });
+            auto const [from, to] = translateToCellRange(motion, count).ordered();
+            executeYank(from, to);
```
Comment (Yaraslaut) [inline src/vtbackend/ViCommands.cpp:353]: oh, interesting :)

**Review by Yaraslaut — APPROVED** [review]
LGTM, thanks

File: src/vtbackend/ViCommands.cpp (hunk 1 above)
Comment (christianparpart) [reply src/vtbackend/ViCommands.cpp:353]: @Yaraslaut ordering wasn't the problem. That's for cleanness only. The problem was the off-by-on issue in the old code (and NOT being ordered), yielding in the `0` from `y0` pointing to the column `-1`. We did not need to -1 to begin with. I've tested it in with various possibilities, and added that test here as this was the one failing
